web-app/RideApp/urls.py
from django.urls import path
from .views import DriverOrderListView, DriverOrderDetailView, OrderDetailView, OrderListView, OrderCreateView, OrderUpdateView, OrderDeleteView, DriverUpdateForm, SharerOrderListView
from . import views


# urlpatterns = [
#     #path('', views.index, name='index'),#对应<a href="{% url 'index' %}">Home</a>.
#     path('', views.welcome, name='welcome'),
#     path('index/', views.index,name='index'),
# ]

app_name = 'RideApp'
urlpatterns = [
    path('', views.home, name='home'),
    path('home/', views.home, name='home'),
    path('driver/', views.driver_home, name='driver-home'),
    path('driver/search/', views.driver_search, name='driver-search'),
    path('driver/orders/<int:pk>/', DriverOrderListView.as_view(), name='driver-orders'),
    path('order/<int:pk>/detail/', DriverOrderDetailView.as_view(), name='driver-order-detail'),
    path('driver/order_confirm/<int:pk>/', views.driver_confirm, name='driver-order-confirm'),
    path('driver/order_complete/<int:pk>/', views.driver_complete, name='driver-order-complete'),
    path('driver/update/', views.driver_update, name='driver-update'),
    path('driver/info/<int:pk>', views.driver_info, name='driver-info'),


    path('home/userAllRequest/', OrderListView.as_view(), name='userAllRequest'),
    path('home/createRequest/', OrderCreateView.as_view(), name='order_form'),
    path('home/userAllRequest/order/<int:pk>/', OrderDetailView.as_view(), name='order-detail'),
    path('home/userAllRequest/order/<int:pk>/update/', OrderUpdateView.as_view(), name='order-update'),
    path('home/userAllRequest/order/<int:pk>/delete/', OrderDeleteView.as_view(), name='order-delete'),


    path('sharer/search/', views.sharer_search, name='sharer-search'),
    path('sharer/join/<int:order_pk>/<int:sharer_pk>/', views.sharer_join, name='sharer-join'),
    path('sharer/home/', views.sharer_home, name='sharer-home'),
    path('sharer/list/<int:pk>', SharerOrderListView.as_view(), name='sharer-list'),
]

web-app/p1d2/urls.py
from django.contrib import admin
from django.urls import include, path
from RideApp import views as rideapp_views
from django.contrib.auth import views as auth_views
#  127.0.0.1:8000/
urlpatterns = [
    path('admin/', admin.site.urls),
    path('register/',rideapp_views.register, name='register'),
    path('login/',auth_views.LoginView.as_view(template_name='RideApp/login.html'), name='login'),
    path('logout/',auth_views.LogoutView.as_view(template_name='RideApp/logout.html'), name='logout'),
    path('', include('RideApp.urls')),
]

web-app/RideApp/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse


class RideUser(models.Model):
    person = models.OneToOneField(User, on_delete=models.CASCADE)
    is_driver = models.BooleanField(default=False)
    vehicle_type = models.CharField(max_length=50,null=True,blank=True,help_text="user's vehicle type")
    special_request = models.CharField(max_length=50,null=True,blank=True,help_text="user's special reequest")
    max_car_pass = models.IntegerField(null=True,blank=True,help_text="car's max passenger")
    license_plate_number = models.CharField(max_length=50,null=True,blank=True,help_text="user's license_plate_number")

    def __str__(self):
        return self.person.username


class Order(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='owner')#owener
    driver = models.ForeignKey(User, on_delete=models.CASCADE,null=True,related_name='driver')#driver
    dst = models.CharField(max_length=200, verbose_name='Destination')
    arrivial_time = models.DateTimeField(help_text='Format: 2020-01-01 12:00', null=True)
    order_pass_num = models.IntegerField(null=True,default=0)
    is_share = models.BooleanField(default=False)
    owner_pass_num = models.IntegerField(null=True,default=0)
    special_request = models.TextField(max_length=200, help_text="Do you have any other requests",null=True, blank=True,
                                       default='null')  # match info
    special_vehicle_type = models.CharField(max_length=200, help_text="Car type", null=True, blank=True,
                                            default='null')  # match info



    STATUS = (
        ('open', 'open'),
        ('confirm', 'confirm'),
        ('complete', 'complete'),
    )

    status = models.CharField(max_length=20, choices=STATUS, default='open')

    def __str__(self):
        return self.dst

    def get_absolute_url(self):
        return reverse('RideApp:order-detail', kwargs={'pk': self.pk})  # 一定要加rideapp:,不然找不到


class Sharer(models.Model):
    sharer = models.ForeignKey(User, on_delete=models.CASCADE)
    request = models.ForeignKey(Order, on_delete=models.CASCADE, null=True)
    share_pass_num = models.IntegerField(null=True, default=0)
    early_time = models.DateTimeField(verbose_name='Early acceptable arrive date', help_text='Format: 2020-01-01 12:00')
    last_time = models.DateTimeField(verbose_name='Latest acceptable arrive date', help_text='Format: 2020-01-01 12:00')

    def __str__(self):
        return self.sharer.username

web-app/RideApp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .models import RideUser


# class UserRegisterForm(UserCreationForm):
#     email = forms.EmailField()
#
#     class Meta:
#         model = User
#         fields = ['username', 'email', 'password1', 'password2']
#
#         # fields = ['username','email','password1',"is_driver","vehicle_type", "license_plate_number", "max_car_pass",
#         # "special_request"]

class UserRegisterForm(UserCreationForm):
    email = forms.EmailField()

    class Meta:
        model = User
        fields = ['username', 'email', 'password1', 'password2']

        # fields = ['username','email','password1',"is_driver","vehicle_type", "license_plate_number", "max_car_pass",
        # "special_request"]


class DriverSearchForm(forms.Form):
    vehicle_capacity = forms.IntegerField()
    vehicle_type = forms.CharField(initial='null', help_text='if no special requirement, please stay null')
    special_request = forms.CharField(initial='null', help_text='if no special requirement, please stay null')


# class DriverUpdateForm(forms.Form):
#     is_driver = forms.BooleanField()
#     vehicle_type = forms.CharField(initial='null', help_text="user's vehicle type")
#     special_request = forms.CharField(initial='null', help_text="user's special request")
#     max_car_pass = forms.IntegerField(help_text="car's max passenger")
#     license_plate_number = forms.CharField(help_text="user's license_plate_number")

class DriverUpdateForm(forms.ModelForm):
    class Meta:
        model = RideUser
        fields = ('is_driver','vehicle_type','special_request','max_car_pass','license_plate_number')


class SharerSearchForm(forms.Form):
    dst = forms.CharField()
    early_time = forms.DateTimeField(help_text='Format: 2020-01-01 12:00')
    last_time = forms.DateTimeField(help_text='Format: 2020-01-01 12:00')
    share_pass_num = forms.IntegerField()

web-app/RideApp/views.py
from django.contrib.auth.models import User
from django.views.generic import ListView, DetailView

from .models import Order, RideUser, Sharer
from django.views import generic
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.contrib.auth.decorators import login_required
from django.shortcuts import get_object_or_404, render, redirect
from django.urls import reverse, reverse_lazy
from django.core.mail import send_mail
from django.utils import timezone as datetime
from datetime import datetime
from django.contrib import messages
import datetime
from django.contrib.auth.forms import UserCreationForm
from .forms import UserRegisterForm, DriverUpdateForm, SharerSearchForm


def register(request):
    if request.method == 'POST':
        form = UserRegisterForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            messages.success(request, f'Account created for {username}!')
            return redirect('RideApp:home')
    else:
        form = UserRegisterForm()
    return render(request, 'RideApp/register.html', {'form': form})


def home(request):
    return render(request, 'RideApp/home.html')


class OrderListView(generic.ListView):
    model = Order
    template_name = 'RideApp/userAllRequest.html'
    context_object_name = 'orders'



class OrderDetailView(generic.DetailView):
    model = Order


class OrderCreateView(LoginRequiredMixin, generic.CreateView):
    model = Order
    # name = model.owner.username

    fields = ['dst', 'arrivial_time', 'is_share', 'owner_pass_num', 'special_request', 'special_vehicle_type']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.order_pass_num = self.request.POST.get('owner_pass_num')
        return super().form_valid(form)  # 将当前用户变成owner


class OrderUpdateView(LoginRequiredMixin, UserPassesTestMixin, generic.UpdateView):
    model = Order
    # name = model.owner.username

    fields = ['dst', 'arrivial_time', 'is_share', 'owner_pass_num', 'special_request', 'special_vehicle_type']

    def form_valid(self, form):
        form.instance.owner = self.request.user
        form.instance.order_pass_num = self.request.POST.get('owner_pass_num')
        return super().form_valid(form)  # 将当前用户变成owner


    def test_func(self):  # in case other user change the file
        order = self.get_object()
        if order.owner == self.request.user:
            if order.status == 'open':
                return True
        return False


class OrderDeleteView(LoginRequiredMixin, UserPassesTestMixin, generic.DeleteView):
    model = Order
    success_url = reverse_lazy('RideApp:userAllRequest')  # 删除成功后，页面回到哪里

    def test_func(self):
        order = self.get_object()
        if self.request.user == order.owner:
            if order.status != 'confirm':
                return True
        return False



# divide
# divide
# divide
# divide



#  views for driver
@login_required
def driver_home(request):
    user = request.user
    if RideUser.objects.filter(person=user).exists():
        ride_user = get_object_or_404(RideUser, person=user)
        if ride_user.is_driver:
            return render(request, 'RideApp/driver_home.html')
        else:
            return redirect('RideApp:driver-update')
    else:
        return redirect('RideApp:driver-update')



class DriverOrderListView(ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'RideApp/driver_lists.html'

    def get_queryset(self):
        user = get_object_or_404(User, pk=self.kwargs.get('pk'))
        return Order.objects.filter(driver=user, status='confirm')


class DriverOrderDetailView(DetailView):
    model = Order
    template_name = 'RideApp/driver_list_detail.html'

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        order = get_object_or_404(Order, pk=self.kwargs.get('pk'))
        sharer_list = order.sharer_set.all()
        # Add in a QuerySet of all the books
        context['sharer_list'] = sharer_list
        return context


@login_required
def driver_search(request):
        rideuser = request.user.rideuser
        open_order = Order.objects.filter(status="open")
        selected_orders = open_order.filter(order_pass_num__range=(0, rideuser.max_car_pass), special_request=rideuser.special_request, special_vehicle_type=rideuser.vehicle_type)
        # 不能接自己的单 owner 或 sharer 是自己
        selected_orders = selected_orders.exclude(owner=request.user)

        for order in selected_orders:
            sharer_list = order.sharer_set.all()
            for sharer in sharer_list:
                if sharer is request.user:
                    selected_orders = selected_orders.exclude(order)

        return render(request, 'RideApp/selected_order_list.html', {'selected_orders': selected_orders})


@login_required
def driver_confirm(request, pk):
    order = get_object_or_404(Order, pk=pk)
    user = request.user
    order.status = 'confirm'
    order.driver = user
    order.save()
    if order.status == 'confirm':
        messages.success(request, f'Your have confirm the order!')
        subject = 'Order has been confirmed!'
        message = 'please wait for driver picking up.'
        from_email = 'luq1016@outlook.com'
        sharerSet = Sharer.objects.filter(request=order)
        to_list = [order.owner.email]
        send_mail(subject, message, from_email, to_list, fail_silently=False)
        for ssharer in sharerSet:
            send_mail(subject, message, from_email, [ssharer.sharer.email], fail_silently=False)
    return redirect('RideApp:driver-home')


@login_required
def driver_complete(request, pk):
    order = get_object_or_404(Order, pk=pk)
    order.status = 'complete'
    order.save()
    if order.status == 'complete':
        messages.success(request, f'Your have complete the order!')
    return redirect('RideApp:driver-home')


def driver_update(request):
    try:
        rideuser = request.user.rideuser
    except RideUser.DoesNotExist:
        rideuser = RideUser(person=request.user)

    if request.method == 'POST':
        form = DriverUpdateForm(request.POST, instance=rideuser)
        if form.is_valid():
            form.save()
            messages.success(request, f'Your has  become a driver!')
            return redirect('RideApp:driver-home')
    else:
        form = DriverUpdateForm(instance=rideuser)
        context = {
            'form': form,
        }
    return render(request, 'RideApp/driver_update.html', context)


def driver_info(request, pk):
    order = get_object_or_404(Order, pk=pk)
    driver = order.driver.rideuser
    vehicle_type = driver.vehicle_type
    max_car_pass = driver.max_car_pass
    license_plate_number = driver.license_plate_number
    special_request = driver.special_request
    context = { 'vehicle_type': vehicle_type,
                'max_car_pass': max_car_pass,
                'license_plate_number': license_plate_number,
                'special_request': special_request,
    }
    return render(request, 'RideApp/driver_info.html', context)


#  divide
#  divide
#  divide



#  sharer 不能找到自己的 订单 && 自己加过的订单

@login_required
def sharer_search(request):
    if request.method == 'POST':
        form = SharerSearchForm(request.POST)
        if form.is_valid():
            dst = form.cleaned_data.get('dst')
            early_time = form.cleaned_data.get('early_time')
            last_time = form.cleaned_data.get('last_time')
            share_pass_num = form.cleaned_data.get('share_pass_num')
            sharer = Sharer(sharer=request.user, share_pass_num=share_pass_num, early_time=early_time, last_time=last_time)
            sharer.save()
            open_order = Order.objects.filter(status="open")
            selected_orders = open_order.filter(arrivial_time__range=(early_time, last_time),
                                                dst=dst, is_share=True, status='open')
            selected_orders = selected_orders.exclude(owner=request.user)
            for order in selected_orders:
                sharer_list = order.sharer_set.all()
                if sharer_list.filter(pk=sharer.pk).exists():
                    selected_orders.exclude(pk=order.pk)
                if order.owner == request.user:
                    selected_orders.exclude(pk=order.pk)

            context = {'selected_orders': selected_orders, 'sharer_pk': sharer.pk}
            return render(request, 'RideApp/sharer_orders.html', context)
    else:
        form = SharerSearchForm()
    return render(request, 'RideApp/sharer_search.html', {'form': form})


#  通过 user && order 找到对应 的sharer
@login_required
def sharer_join(request, order_pk, sharer_pk):
    order = get_object_or_404(Order, pk=order_pk)
    sharer = Sharer.objects.get(pk=sharer_pk)
    sharer.request = order
    sharer.save()
    order.order_pass_num += sharer.share_pass_num
    order.save()
    if sharer.request == order:
        messages.success(request, f'Your have join the order!')
    return redirect('RideApp:home')


@login_required
def sharer_home(request):

    return render(request, 'RideApp/sharer_home.html')


class SharerOrderListView(ListView):
    model = Order
    context_object_name = 'orders'
    template_name = 'RideApp/sharer_lists.html'

    def get_queryset(self):
        user = get_object_or_404(User, pk=self.kwargs.get('pk'))
        sharer_list = user.sharer_set.all()
        order_list = Order.objects.all()
        for sharer in sharer_list:
            if sharer.request:
                order_list = order_list.exclude(pk=sharer.request.pk)
        ret = Order.objects.all()
        for order in order_list:
            ret = ret.exclude(pk=order.pk)
        return ret

web-app/RideApp/templates/RideApp/driver_home.html
{% extends "RideApp/base.html" %}
{% block content %}
    <h1>Driver Page</h1>
  <br>
        What you want to do?
    <div class="media-body">
      <div class="article-metadata">
        <br><a class="mr-2" href="{% url 'RideApp:driver-orders' user.pk%}">View the confirmed order</a>
          <br><a class="mr-2" href="{% url 'RideApp:driver-search' %}">Start a new order</a>
      </div>
    </div>

{% endblock content %}

web-app/RideApp/templates/RideApp/driver_list_detail.html
{% extends "RideApp/base.html" %}
{% block content %}
 <ul class="list-group">
  <li class="list-group-item">Owner: {{ object.owner }}</li>
  <li class="list-group-item">Destination: {{ object.dst }}</li>
  <li class="list-group-item">Arrival Time: {{ object.arrivial_time|date:"F d, Y H:i:s"}}</li>
  <li class="list-group-item">Total Passenger Number: {{ object.order_pass_num }}</li>
  <li class="list-group-item">Special Request: {{ object.special_request }}</li>
  <li class="list-group-item">Special Vehicle Type: {{ object.special_vehicle_type }}</li>
   <li class="list-group-item">Status: {{ object.status }}</li>
     {% if object.is_share == True %}
          {% for sharer in sharer_list %}
              <li class="list-group-item">Sharer Destination: {{ sharer.request.dst }}</li>
              <li class="list-group-item">Sharer Number: {{ sharer.share_pass_num }}</li>
          {% endfor %}
     {% endif %}
</ul>
{% endblock content %}

web-app/RideApp/templates/RideApp/driver_lists.html
{% extends "RideApp/base.html" %}
{% block content %}
    {%  for order in orders %}
       <div class="list-group">
            <a href="{% url 'RideApp:driver-order-detail' order.pk %}" class="list-group-item">
                Order : {{order.dst}} supposed to be arrived at {{ order.arrival_time }}
             </a>
        </div>
        <a href="{% url 'RideApp:driver-order-complete' order.pk %}">
            <button>Complete</button>
        </a>
    {% endfor %}
    <br>
    <div>
        <a href="{% url 'RideApp:driver-home' %}">
            <button>Back to home</button>
        </a>
    </div>
{% endblock content %}

web-app/RideApp/templates/RideApp/driver_search.html
{% extends "RideApp/base.html" %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="content-section">
       <form method="POST">
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Please search your desired order</legend>
               {{ form|crispy }}
               <div class="form-group">
                   <button class="btn btn-outline-info">Search</button>
               </div>
           </fieldset>
       </form>

       <div class="border-top pt-3">
           <small class="text-muted">
               Do not want to be a driver? <a class="ml-2" href="{% url 'RideApp:home' %}"></a>
           </small>
       </div>

   </div>
{% endblock content %}

web-app/RideApp/templates/RideApp/driver_update.html
{% extends "RideApp/base.html" %}
{% load crispy_forms_tags %}
{% block content %}
  <div class="content-section">
    <h2 class="account-heading">{{user.username}}</h2>

    <form method="POST">
      {% csrf_token %}
      <fieldset class="form-group">
        <legend class="border-bottom mb-4">Driver Info</legend>
        {{ form|crispy }}
        <div class="form-group">
          <button class="btn btn-outline-info">Update</button>
        </div>
      </fieldset>
    </form>
  </div>
{% endblock content %}

web-app/RideApp/templates/RideApp/home.html
{% extends "RideApp/base.html" %}
{% block content %}
    <h1>Home Page</h1>

    <div class="media-body">
      <div class="article-metadata">
           {% if user.is_authenticated %}
                 <br>
                     Select your role
               <br><a class="mr-2" href="{% url 'RideApp:userAllRequest' %}">As a user</a>
               <br><a class="mr-2" href="{% url 'RideApp:driver-home' %}">As a driver</a>
               <br><a class="mr-2" href="{% url 'RideApp:sharer-home' %}">As a sharer</a>
           {% else %}
               <br>
                     Welcome! Have no account?
               <a class="nav-item nav-link" href="{% url 'register' %}">Please register!</a>
               <br>
                     Already have an account?
               <a class="nav-item nav-link" href="{% url 'login' %}">Please login!</a>
           {% endif %}
      </div>
    </div>

{% endblock content %}

web-app/RideApp/templates/RideApp/login.html
{% extends "RideApp/base.html" %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Login</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                   Login
                </button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Need an Account? <a class="ml-2" href="{% url  'register' %}">Sign up</a>
            </small>
        </div>
    </div>

{% endblock %}

web-app/RideApp/templates/RideApp/logout.html
{% extends "RideApp/base.html" %}
{% block content %}
    <h2>You have been successfully logged out</h2>
    <div class="border-top pt-3">
        <small class="text-muted">
            <a href="{% url 'login' %}">Log In Again</a>
        </small>
    </div>
{% endblock content %}

web-app/RideApp/templates/RideApp/order_detail.html
{% extends "RideApp/base.html" %}
{% block content %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <p class="mr-2">Owner: {{ object.owner.username}}</p>
              <small class="text-muted">Time: {{ object.arrivial_time|date:"F d, Y H:i:s" }}</small><!--detailview expects object called objects-->
                {% if object.owner == user %}
                {% if object.status == 'open' %}
          <div>

            <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'RideApp:order-update' object.id%}">Update</a>
            <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'RideApp:order-delete' object.id%}">Delete</a>
          </div>
                    {% endif %}
        {% endif %}
            </div>
            <h2><p class="article-title" >Destination: {{ object.dst }}</p></h2>
            <p class="article-content">Order passenger number: {{ object.order_pass_num }}</p>
              <p class="article-content">Owner passenger number: {{ object.owner_pass_num }}</p>
              <p class="article-content">Are you willing to share with others? {{ object.is_share }}</p>
              <p class="article-content">Driver's name: {{ object.driver.username }}</p><!--好像不可以 这样-->
              <p class="article-content">Special request: {{ object.special_request }}</p>
              <p class="article-content">Vehicle type info: {{ object.special_vehicle_type }}</p>
              <p class="article-content">Order status: {{ object.status }}</p>
          </div>
        </article>
{% endblock content %}

web-app/RideApp/templates/RideApp/register.html
{% extends "RideApp/base.html" %}

{% block content %}
    {% load crispy_forms_tags %}
    <div class="content-section">
        <form method="post">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4"> Join Us Today!</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">
                    Sign Up
                </button>
            </div>
        </form>
        <div class="border-top pt-3">
            <small class="text-muted">
                Already Have An Account? <a class="ml-2" href="#">Sign In</a>
            </small>
        </div>
    </div>

{% endblock %}

web-app/RideApp/templates/RideApp/selected_order_list.html
{% extends "RideApp/base.html" %}
{% block content %}
    {%  for order in selected_orders %}
        <div>
            <article class="content-section">
                <h2 class="article-title">Destination: {{ order.dst }}</h2>
                <p class="article-content">Arrival Time: {{ order.arrivial_time|date:"F d, Y H:i:s" }}</p>
                <p class="article-content">Passenger Number: {{ order.order_pass_num }}</p>
                <p class="article-content">Special Request: {{ order.special_request }}</p>
                <p class="article-content">Vehicle Type: {{ order.special_vehicle_type }}</p>
            </article>
        </div>
        <a href="{% url 'RideApp:driver-order-confirm' order.pk %}">
            <button>Confirm</button>
        </a>
    {% endfor %}
    <br>
    <div>
        <a href="{% url 'RideApp:driver-home' %}">
            <button>Back</button>
        </a>
    </div>
{% endblock content %}

web-app/RideApp/templates/RideApp/sharer_home.html
{% extends "RideApp/base.html" %}
{% block content %}
    <h1>Share Page</h1>
  <br>
        What you want to do?
    <div class="media-body">
      <div class="article-metadata">
        <br><a class="mr-2" href="{% url 'RideApp:sharer-list' user.pk %}">View the joined order</a>
          <br><a class="mr-2" href="{% url 'RideApp:sharer-search' %}">Join an order</a>
      </div>
    </div>

{% endblock content %}

web-app/RideApp/templates/RideApp/sharer_search.html
{% extends "RideApp/base.html" %}
{% block content %}
    {% load crispy_forms_tags %}
    <div class="content-section">
       <form method="POST">
           {% csrf_token %}
           <fieldset class="form-group">
               <legend class="border-bottom mb-4">Please search your desired order</legend>
               {{ form|crispy }}
               <div class="form-group">
                   <button class="btn btn-outline-info">Search</button>
               </div>
           </fieldset>
       </form>

   </div>
{% endblock content %}

web-app/RideApp/templates/RideApp/userAllRequest.html
{% extends "RideApp/base.html" %}
{% block content %}
    {% for order in orders %}
        {% if order.owner == user %}
        <article class="media content-section">
          <div class="media-body">
            <div class="article-metadata">
              <a class="mr-2" href=" ">Owner: {{ order.owner.username}}</a >
              <small class="text-muted">Time: {{ order.arrivial_time|date:"F d, Y H:i:s" }}</small>
            </div>

            <h2><a class="article-title" href="{% url 'RideApp:order-detail' order.id %}">Destination: {{ order.dst }}</a ></h2>

              <p class="article-content">Order's number: {{ order.order_pass_num }}</p >
              <p class="article-content">Are you willing to share with others? {{ order.is_share }}</p >
              <p class="article-content">Special request: {{ order.special_request }}</p >
              <p class="article-content">Vehicle type info: {{ order.special_vehicle_type }}</p >
              <p class="article-content">Order status: {{ order.status }}</p >
               {% if order.status == 'confirm' %}
                    <p class="article-content">Driver's name: {{ order.driver.username }}</p >
                   <a class="article-content" href="{% url 'RideApp:driver-info' order.pk %}">Driver and car's detail</a >
                {% endif %}
          </div>
        </article>
        {% endif %}
    {% endfor %}
{% endblock content %}